name: Monthly Spreadsheet Sync

on:
  schedule:
    # 8 AM UTC == 12 AM Pacific Time (PST/PDT adjusted)
    # Run at 8:00 AM UTC = 12:00am PST on the 1st day of every month (Changes on DayLight Savings)
    - cron: '0 8 1 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_csvs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download CSVs from Google Sheets
        run: |
          SHEET_ID="1u7-7kIAtv2q_gIUCcSp6hZdR_Nv0HGgg_wWNZ68I9kY"

          declare -A tabs
          tabs=(
            ["dependency_graph"]="1561882666"
            ["units"]="2013487824"
            ["videos"]="1238287991"
          )

          mkdir -p public/data

          for name in "${!tabs[@]}"; do
            echo "Downloading ${name}.csv..."
            curl -L -o "public/data/${name}.csv" \
              "https://docs.google.com/spreadsheets/d/${SHEET_ID}/export?format=csv&gid=${tabs[$name]}"
          done

      - name: Commit and push if changes detected
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/data/*.csv

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            changed=$(git diff --cached --name-only | xargs)
            git commit -m "Updated CSVs: ${changed}"
            git push
          fi
